[package]
name = "sui-data-store"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
chrono.workspace = true
csv.workspace = true
cynic.workspace = true
fastcrypto.workspace = true
lru.workspace = true
move-core-types.workspace = true
mysten-common.workspace = true
prost-types.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json.workspace = true
sui-framework.workspace = true
sui-json-rpc-types.workspace = true
sui-rpc.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
tracing.workspace = true

[build-dependencies]
cynic-codegen.workspace = true
